name: Front Box check Build

on:
    pull_request:
      branches:
        - main
jobs:
    build:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.9.0
            - name: Npm Install
              run: npm install
            
            - name: Check eslint
              run: npm run lint:fix
            
            - name: Check Ts
              run: npm run check:ts
            
            - name: Build 
              run: npm run build
            
            